CREATE DATABASE`Projekti_db` DEFAULT CHARACTER SET latin1 ;
tai (schema ja database ovat toistensa synonyymejä MySQL:ssä)
CREATE SCHEMA `Projekti_db` DEFAULT CHARACTER SET latin1 ;

CREATE TABLE `Projekti_db`.`TYONTEKIJA` (
	TYONTEKIJANRO CHAR(6) NOT NULL PRIMARY KEY,
	ETUNIMI VARCHAR(12) NOT NULL,
	TOINENNIMI CHAR(1),
	SUKUNIMI VARCHAR(15) NOT NULL,
	OSASTO CHAR(3),
	PUHELINNUMERO CHAR(15),
	TOIDENALOITUSPVM DATE,
	TYOTEHTAVA CHAR(15),
	SUKUPUOLI CHAR(1),
	SYNTYMAPVM DATE,
	PALKKA DECIMAL(9,2),
	BONUKSET DECIMAL(9,2)
) ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


CREATE TABLE Projekti_db.OSASTO (
	OSASTONRO CHAR(3) NOT NULL PRIMARY KEY,
	NIMI VARCHAR(36) NOT NULL,
	PAALLIKKO CHAR(6),
	SIJAINTI CHAR(50) NOT NULL,
	FOREIGN KEY (PAALLIKKO) REFERENCES TYONTEKIJA(TYONTEKIJANRO)
)ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

ALTER TABLE Projekti_db.TYONTEKIJA
        ADD CONSTRAINT CONSTR_OSASTO_TYONTEK1
         FOREIGN KEY (OSASTO)
           REFERENCES OSASTO(OSASTONRO)
              ON DELETE SET NULL;

CREATE TABLE Projekti_db.PROJEKTI (
	PROJEKTINRO CHAR(6) NOT NULL PRIMARY KEY,
	NIMI VARCHAR(24) NOT NULL,
	OSASTONRO CHAR(3) NOT NULL,
	VASTUUHENKILO CHAR(6) NOT NULL,
	ALOITUSPVM DATE,
	LOPETUSPVM DATE,
	PAAPROJEKTINRO CHAR(6),
	FOREIGN KEY (OSASTONRO) REFERENCES OSASTO(OSASTONRO),
	FOREIGN KEY (VASTUUHENKILO) REFERENCES TYONTEKIJA(TYONTEKIJANRO)
)ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE TABLE Projekti_db.TYONTEKIJA_PROJEKTISSA (
	TYONTEKIJANRO CHAR(6) NOT NULL,	
	PROJEKTINRO CHAR(6) NOT NULL,
	TEHTAVANRO SMALLINT NOT NULL,
	KESTO DECIMAL(5,2),
	ALOITUSPVM DATE,
	LOPETUSPVM DATE,
	FOREIGN KEY (TYONTEKIJANRO) REFERENCES TYONTEKIJA(TYONTEKIJANRO),
	FOREIGN KEY (PROJEKTINRO) REFERENCES PROJEKTI(PROJEKTINRO)
)ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

