CREATE DATABASE [Projekti_db] ON  PRIMARY 
( NAME = N'Projekti_db', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.MSSQLSERVER\MSSQL\DATA\Projekti_db.mdf' , SIZE = 2048KB , MAXSIZE = 204800KB , FILEGROWTH = 10240KB )
 LOG ON 
( NAME = N'Projekti_db_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.MSSQLSERVER\MSSQL\DATA\Projekti_db_log.ldf' , SIZE = 1024KB , MAXSIZE = 102400KB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Projekti_db] SET RECOVERY BULK_LOGGED;

CREATE TABLE TYONTEKIJA (
	TYONTEKIJANRO CHAR(6) NOT NULL PRIMARY KEY,
	ETUNIMI VARCHAR(12) NOT NULL,
	TOINENNIMI CHAR(1),
	SUKUNIMI VARCHAR(15) NOT NULL,
	OSASTO CHAR(3),
	PUHELINNUMERO CHAR(15),
	TOIDENALOITUSPVM DATE,
	TYOTEHTAVA CHAR(15),
	SUKUPUOLI CHAR(1),
	SYNTYMAPVM DATE,
	PALKKA DECIMAL(9,2),
	BONUKSET DECIMAL(9,2)
);	

CREATE TABLE OSASTO (
	OSASTONRO CHAR(3) NOT NULL PRIMARY KEY,
	NIMI VARCHAR(36) NOT NULL,
	PAALLIKKO CHAR(6),
	SIJAINTI CHAR(50) NOT NULL,
	FOREIGN KEY (PAALLIKKO) REFERENCES TYONTEKIJA(TYONTEKIJANRO)
);

ALTER TABLE TYONTEKIJA
        ADD CONSTRAINT CONSTR_OSASTO_TYONTEK1
         FOREIGN KEY (OSASTO)
           REFERENCES OSASTO(OSASTONRO)
              ON DELETE SET NULL;

CREATE TABLE PROJEKTI (
	PROJEKTINRO CHAR(6) NOT NULL PRIMARY KEY,
	NIMI VARCHAR(24) NOT NULL,
	OSASTONRO CHAR(3) NOT NULL,
	VASTUUHENKILO CHAR(6) NOT NULL,
	ALOITUSPVM DATE,
	LOPETUSPVM DATE,
	PAAPROJEKTINRO CHAR(6),
	FOREIGN KEY (OSASTONRO) REFERENCES OSASTO(OSASTONRO),
	FOREIGN KEY (VASTUUHENKILO) REFERENCES TYONTEKIJA(TYONTEKIJANRO)
);

CREATE TABLE TYONTEKIJA_PROJEKTISSA (
	TYONTEKIJANRO CHAR(6) NOT NULL,	
	PROJEKTINRO CHAR(6) NOT NULL,
	TEHTAVANRO SMALLINT NOT NULL,
	KESTO DECIMAL(5,2),
	ALOITUSPVM DATE,
	LOPETUSPVM DATE,
	FOREIGN KEY (TYONTEKIJANRO) REFERENCES TYONTEKIJA(TYONTEKIJANRO),
	FOREIGN KEY (PROJEKTINRO) REFERENCES PROJEKTI(PROJEKTINRO)
);
