INSERT INTO `Projekti_db`.`OSASTO` (`OSASTONRO`, `NIMI`, `SIJAINTI`) VALUES ('10', 'Myynti', 'Helsinki');
INSERT INTO `Projekti_db`.`OSASTO` (`OSASTONRO`, `NIMI`, `SIJAINTI`) VALUES ('20', 'Varasto', 'Vantaa');

INSERT INTO `Projekti_db`.`TYONTEKIJA` (`TYONTEKIJANRO`, `ETUNIMI`, `TOINENNIMI`, `SUKUNIMI`, `OSASTO`, `PUHELINNUMERO`, `TOIDENALOITUSPVM`, `TYOTEHTAVA`, `SUKUPUOLI`, `SYNTYMAPVM`, `PALKKA`, `BONUKSET`) VALUES ('1', 'Maija', 'Sini', 'Poppanen', '10', '0423349123', '2000-01-31', 'Tuotevastaava', 'N', '1990-06-30', '3000', '0');
INSERT INTO `Projekti_db`.`TYONTEKIJA` (`TYONTEKIJANRO`, `ETUNIMI`, `TOINENNIMI`, `SUKUNIMI`, `OSASTO`, `PUHELINNUMERO`, `TOIDENALOITUSPVM`, `TYOTEHTAVA`, `SUKUPUOLI`, `SYNTYMAPVM`, `PALKKA`, `BONUKSET`) VALUES ('2', 'Ville', 'Jani', 'Peltonen', '20', '0425556667', '2010-07-30', 'Varastoesimies', 'M', '1985-02-15', '3000', '1');
INSERT INTO `Projekti_db`.`TYONTEKIJA` (`TYONTEKIJANRO`, `ETUNIMI`, `TOINENNIMI`, `SUKUNIMI`, `OSASTO`, `PUHELINNUMERO`, `TOIDENALOITUSPVM`, `TYOTEHTAVA`, `SUKUPUOLI`, `SYNTYMAPVM`, `PALKKA`, `BONUKSET`) VALUES ('3', 'Pekka', 'Toni', 'Niemi', '20', '0421112223', '2010-08-1', 'Ostaja', 'M', '1991-10-01', '3000', '0');
INSERT INTO `Projekti_db`.`TYONTEKIJA` (`TYONTEKIJANRO`, `ETUNIMI`, `TOINENNIMI`, `SUKUNIMI`, `OSASTO`, `PUHELINNUMERO`, `TOIDENALOITUSPVM`, `TYOTEHTAVA`, `SUKUPUOLI`, `SYNTYMAPVM`, `PALKKA`) VALUES ('4', 'Milla', 'Janika', 'Virta', '10', '0423322110', '2011-01-14', 'Myyjä', 'N', '1990-07-09', '3000');

INSERT INTO `Projekti_db`.`PROJEKTI` (`PROJEKTINRO`, `NIMI`, `OSASTONRO`, `VASTUUHENKILO`, `ALOITUSPVM`, `LOPETUSPVM`, `PAAPROJEKTINRO`) VALUES ('100', 'Itella 1', '10', '1', '2012-09-01', '2012-12-31', '1');
INSERT INTO `Projekti_db`.`PROJEKTI` (`PROJEKTINRO`, `NIMI`, `OSASTONRO`, `VASTUUHENKILO`, `ALOITUSPVM`, `LOPETUSPVM`) VALUES ('101', 'Neste Oil', '10', '1', '2012-10-5', '2013-01-31');


INSERT INTO `Projekti_db`.`TYONTEKIJA_PROJEKTISSA` (`TYONTEKIJANRO`, `PROJEKTINRO`, `TEHTAVANRO`, `KESTO`, `ALOITUSPVM`, `LOPETUSPVM`) VALUES ('1', '100', '1', '4', '2012-09-01', '2012-09-07');
INSERT INTO `Projekti_db`.`TYONTEKIJA_PROJEKTISSA` (`TYONTEKIJANRO`, `PROJEKTINRO`, `TEHTAVANRO`, `KESTO`, `ALOITUSPVM`, `LOPETUSPVM`) VALUES ('1', '100', '2', '7', '2012-09-15', '2012-09-20');




