USE [master]
GO

/****** Object:  Database [VideoDB]    Script Date: 03/24/2013 08:59:00 ******/
CREATE DATABASE [VideoDB] ON  PRIMARY 
( NAME = N'Video_DB1', FILENAME = N'c:\Videodata\Videodat1.mdf' , SIZE = 2304KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB ), 
 FILEGROUP [FileStreamGroup1] CONTAINS FILESTREAM  DEFAULT 
( NAME = N'Video_DB2', FILENAME = N'c:\Videodata\filestream1' )
 LOG ON 
( NAME = N'Video_Log1', FILENAME = N'c:\Videodata\Videolog1.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [VideoDB] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [VideoDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [VideoDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [VideoDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [VideoDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [VideoDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [VideoDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [VideoDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [VideoDB] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [VideoDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [VideoDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [VideoDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [VideoDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [VideoDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [VideoDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [VideoDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [VideoDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [VideoDB] SET  ENABLE_BROKER 
GO

ALTER DATABASE [VideoDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [VideoDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [VideoDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [VideoDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [VideoDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [VideoDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [VideoDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [VideoDB] SET  READ_WRITE 
GO

ALTER DATABASE [VideoDB] SET RECOVERY FULL 
GO

ALTER DATABASE [VideoDB] SET  MULTI_USER 
GO

ALTER DATABASE [VideoDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [VideoDB] SET DB_CHAINING OFF 
GO


